project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!Assets/Interactive_Notebooks/"
    - "!docs/"

website:
  favicon: Assets/Images/DS_Logo.png
  sidebar:
    style: "docked"
    background: light
    logo: Assets/Images/DS_Logo.png
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Course Modules"
        contents:
          - text: "Module 1"
            href: modules/module1.qmd
          - text: "Module 2"
            href: modules/module2.qmd
          - text: "Module 3"
            href: modules/module3.qmd
          - text: "Module 4"
            href: modules/module4.qmd
          - text: "Module 5"
            href: modules/module5.qmd
          - text: "Module 6"
            href: modules/module6.qmd
          - text: "Module 7"
            href: modules/module7.qmd
      - section: "Resources"
        contents:
          - text: "Notebooks"
            href: resources/colabs.qmd
          - text: "Reference"
            href: resources/dictionary.qmd
          - text: "Contributors"
            href: resources/contributors.qmd


format:
  html:
    theme: sandstone
    css: 
      - styles.css
      - cosmo-colors.css
    toc: true
    toc-depth: 2
